spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/r505_db
spring.datasource.username=r505_user
spring.datasource.password=e66XDTrE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect